repos:
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2.9007
  hooks:
  - id: use-tidy-description
  - id: style-files
  - id: no-browser-statement
  - id: no-debug-statement
  - id: parsable-R
  - id: deps-in-desc
    files: ^R/.*.R$

